# Generated by Django 4.2.9 on 2024-11-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='capacity',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of guests allowed'),
        ),
    ]
