# Generated by Django 4.2.9 on 2024-11-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='session_limit',
            field=models.PositiveIntegerField(default=4, help_text='Maximum number of guests allowed per booking session (e.g., 4 for shared saunas)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='capacity',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of guests allowed in total'),
        ),
    ]
