# Generated by Django 4.2.9 on 2024-11-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_session_limit_alter_product_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='weekday_closing',
            field=models.TimeField(default='22:00'),
        ),
        migrations.AddField(
            model_name='category',
            name='weekday_opening',
            field=models.TimeField(default='06:00'),
        ),
        migrations.AddField(
            model_name='category',
            name='weekend_closing',
            field=models.TimeField(default='22:00'),
        ),
        migrations.AddField(
            model_name='category',
            name='weekend_opening',
            field=models.TimeField(default='08:00'),
        ),
    ]
